language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: l451ZwgzGvhq9siQma/wOMyiPym1mPbUk9B87IUs6TZ09g3RjZU84A3jGO1M/XVB0eKRQekDjjGfjHk5x6VBCdMuesxVQjk3hw9uoXHtpkcVGlcWC7Sq+GK5P2OqA2GrfD1qWedaVIJX9Gf1ChBKbkPHd+7UaJOO+ecE4Ec2A8iDbXGtLWLxFkYylxCxer/wGtPgWEuy04QonJWSbdBZ+PDRSLBMVwdIz9Rc9L5ofRq7OX3ExY3pBXGhbtnFQ477EwgpQ8CzvWkbaVUnbxbexi/rkBjkXIjcrESMdo14TSOwJNLOH8fKVwvsafQOuUmTNd2YjGUJzQBjDhcGTo+jnYj1I+VIyyQzDiaeF27HYgTCg8yc5jdUP6zfJgjojJv0AhS87AvJZYyvD4vgFRGbZKjOCt1NIyHwKQr68q70PAWLV7HsRDLi41smY4ARuCZjYM28/7EKT6VX3/qrn8oYBh4oaReejX+AYH9oSq32zhWN7XAif4R1ssdDSOZbz7xEh2Smm1IwSONinKNWp1hKVDt16PB4ocxrr5ksZNlHcV6MZhfqs7wAufQFuFYGiG+dUcJGrYC9AES+KUymvhBaLLyOZD8TVspbZYKIkEDD3ERv3OGPG8cwjc9iSoGe1erwlb6Dm8Nc9HLgXy2Gy225fWpKnTZYwOxyr2guebeCuq8=
    on_success: change
